---
apiVersion: v1
kind: Pod
metadata:
  name: downward-api-dynamic-demo
  labels:
    app.kubernetes.io/name: downward-api-dynamic-demo
    status: pending
spec:
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
  containers:
    - name: main-container
      image: busybox:1.37
      command:
        - "sh"
        - "-c"
      args:
        - |
          while true; do
            echo "---";
            echo "Reading labels at $(date):";
            cat /etc/podinfo/labels;
            sleep 10;
          done
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  restartPolicy: Never