apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-01
  labels:
    app.kubernetes.io/name: nfs-storage
    app.kubernetes.io/instance: manual
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/nfs
    server: 192.168.218.13