apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-01
  labels:
    app.kubernetes.io/name: app-config
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v0.0.1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      app.kubernetes.io/instance: manual