---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
#immutable: true
data:
  file1.txt: |
    Текстовый файл 1
    и его
    новое содержимое
  file2.txt: |
    Текстовый файл 2
    и его
    содержимое
