---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/name: app-config
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v0.0.1
data:
  config-template.txt: |
    APP_NAME={{APP_NAME}}
    APP_VERSION={{APP_VERSION}}
    DATABASE_URL={{DATABASE_URL}}
